### ISSUE TITLE
Wikiwand

### ISSUE THREAD

**Issue by borealis999** [d3ward/wel#1]
# Prerequisites

Make sure to answer the following questions before submitting an issue. 

- [ ✓] The extension works or at least the main features seems to work 
- [ ✓] I checked the extension to make sure it works
- [ ✓] The extension is mobile friendly ( responsiveness and elements are sized to viewport )

# Extension details

Name : Wikiwand
Chrome Web Store URL ( optional if the extension is not in the CWS ) : https://chrome.google.com/webstore/detail/wikiwand-wikipedia-modern/emffkefkbkpkgpdeeooapgaicgmcbolj
Official Extension Website ( or GitHub) URL : https://www.wikiwand.com
Extension category ( like security , productivity etc. ) : Productivity / Enhancement
- [ ] The extension have bugs ? If yes describe them below :

--------------------
## Comments or anything else
Wikiwand tends to be a resource hog. People might find that the extension impacts performance or battery life on lower end smartphones (untested).

**Comment by d3ward** [comment]
Added to recent commit
